// PicoClaw - Ultra-lightweight personal AI agent
// Inspired by and based on nanobot: https://github.com/HKUDS/nanobot
// License: MIT
//
// Copyright (c) 2026 PicoClaw contributors
//
// Modified by comgunner (https://github.com/comgunner)
// Custom Fork: https://github.com/comgunner/picoclaw-agents

package tools

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// CodeGeneratorTool generates Go boilerplate code from templates.
type CodeGeneratorTool struct {
	outputDir string
}

// NewCodeGeneratorTool creates a new code generator tool.
func NewCodeGeneratorTool(outputDir string) *CodeGeneratorTool {
	return &CodeGeneratorTool{
		outputDir: outputDir,
	}
}

// Name returns the tool name.
func (t *CodeGeneratorTool) Name() string {
	return "codegen"
}

// Description returns the tool description.
func (t *CodeGeneratorTool) Description() string {
	return "Generate Go boilerplate code from templates (api, service, handler, model, config)"
}

// Parameters returns the tool parameters.
func (t *CodeGeneratorTool) Parameters() map[string]any {
	return map[string]any{
		"type": map[string]any{
			"type":        "string",
			"description": "Type of code to generate: api, service, handler, model, config",
			"enum":        []string{"api", "service", "handler", "model", "config"},
		},
		"name": map[string]any{
			"type":        "string",
			"description": "Name of the component (e.g., UserService, OrderHandler)",
		},
		"package": map[string]any{
			"type":        "string",
			"description": "Package name (default: derived from name)",
			"default":     "",
		},
		"output": map[string]any{
			"type":        "string",
			"description": "Output directory (default: ./generated)",
			"default":     "",
		},
	}
}

// Execute generates the code.
func (t *CodeGeneratorTool) Execute(ctx context.Context, args map[string]any) *ToolResult {
	codeType, ok := args["type"].(string)
	if !ok {
		return ErrorResult("type is required and must be a string")
	}

	name, ok := args["name"].(string)
	if !ok {
		return ErrorResult("name is required and must be a string")
	}

	pkgName, _ := args["package"].(string)
	outputDir, _ := args["output"].(string)

	if outputDir == "" {
		outputDir = t.outputDir
	}
	if outputDir == "" {
		outputDir = "./generated"
	}

	if pkgName == "" {
		pkgName = strings.ToLower(extractBaseName(name))
	}

	// Generate code based on type
	var code string
	var filename string

	switch codeType {
	case "api":
		code, filename = t.generateAPI(name, pkgName)
	case "service":
		code, filename = t.generateService(name, pkgName)
	case "handler":
		code, filename = t.generateHandler(name, pkgName)
	case "model":
		code, filename = t.generateModel(name, pkgName)
	case "config":
		code, filename = t.generateConfig(name, pkgName)
	default:
		return ErrorResult("unknown code type: " + codeType)
	}

	// Create output directory
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return ErrorResult("creating output directory: " + err.Error())
	}

	// Write file
	outputPath := filepath.Join(outputDir, filename)
	if err := os.WriteFile(outputPath, []byte(code), 0o644); err != nil {
		return ErrorResult("writing file: " + err.Error())
	}

	return UserResult(fmt.Sprintf("Generated %s at %s", filename, outputPath))
}

// generateAPI generates an API interface template.
func (t *CodeGeneratorTool) generateAPI(name, pkgName string) (string, string) {
	base := extractBaseName(name)
	code := fmt.Sprintf(`// Code generated by picoclaw codegen. DO NOT EDIT.
// Source: pkg/tools/codegen.go

package %s

import "context"

// %s defines the interface for %s operations.
type %s interface {
	// Get retrieves a %s by ID.
	Get(ctx context.Context, id string) (*%s, error)

	// List returns all %ss.
	List(ctx context.Context) ([]*%s, error)

	// Create creates a new %s.
	Create(ctx context.Context, req *Create%sRequest) (*%s, error)

	// Update updates an existing %s.
	Update(ctx context.Context, id string, req *Update%sRequest) (*%s, error)

	// Delete removes a %s by ID.
	Delete(ctx context.Context, id string) error
}

// %s represents a %s entity.
type %s struct {
	ID        string
	CreatedAt int64
	UpdatedAt int64
}

// Create%sRequest contains parameters for creating a %s.
type Create%sRequest struct {
	// Add fields here
}

// Update%sRequest contains parameters for updating a %s.
type Update%sRequest struct {
	// Add fields here
}
`, pkgName, name, base, name, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base)

	return code, strings.ToLower(base) + "_api.go"
}

// generateService generates a service implementation template.
func (t *CodeGeneratorTool) generateService(name, pkgName string) (string, string) {
	base := extractBaseName(name)
	code := fmt.Sprintf(`// Code generated by picoclaw codegen. DO NOT EDIT.
// Source: pkg/tools/codegen.go

package %s

import (
	"context"
	"time"
)

// %sService implements %s business logic.
type %sService struct {
	// Add dependencies here (e.g., repository, logger)
}

// New%sService creates a new %sService.
func New%sService() *%sService {
	return &%sService{}
}

// Get retrieves a %s by ID.
func (s *%sService) Get(ctx context.Context, id string) (*%s, error) {
	// TODO: Implement
	return nil, nil
}

// List returns all %ss.
func (s *%sService) List(ctx context.Context) ([]*%s, error) {
	// TODO: Implement
	return nil, nil
}

// Create creates a new %s.
func (s *%sService) Create(ctx context.Context, req *Create%sRequest) (*%s, error) {
	entity := &%s{
		ID:        generateID(),
		CreatedAt: time.Now().Unix(),
		UpdatedAt: time.Now().Unix(),
	}

	// TODO: Implement creation logic

	return entity, nil
}

// Update updates an existing %s.
func (s *%sService) Update(ctx context.Context, id string, req *Update%sRequest) (*%s, error) {
	// TODO: Implement
	return nil, nil
}

// Delete removes a %s by ID.
func (s *%sService) Delete(ctx context.Context, id string) error {
	// TODO: Implement
	return nil
}

// generateID generates a unique ID.
func generateID() string {
	// TODO: Use proper ID generation (uuid, nanoid, etc.)
	return "placeholder-id"
}
`, pkgName, base, base, base, name, base, name, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base, base)

	return code, strings.ToLower(base) + "_service.go"
}

// generateHandler generates an HTTP handler template.
func (t *CodeGeneratorTool) generateHandler(name, pkgName string) (string, string) {
	base := extractBaseName(name)
	baseLower := strings.ToLower(base)
	code := fmt.Sprintf(`// Code generated by picoclaw codegen. DO NOT EDIT.
// Source: pkg/tools/codegen.go

package %s

import (
	"encoding/json"
	"net/http"
)

// %sHandler handles HTTP requests for %s operations.
type %sHandler struct {
	service %s
}

// New%sHandler creates a new %sHandler.
func New%sHandler(service %s) *%sHandler {
	return &%sHandler{service: service}
}

// GetHandler handles GET /%s/{id} requests.
func (h *%sHandler) GetHandler(w http.ResponseWriter, r *http.Request) {
	// TODO: Extract ID from URL path
	id := "placeholder-id"

	entity, err := h.service.Get(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	if entity == nil {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(entity)
}

// ListHandler handles GET /%s requests.
func (h *%sHandler) ListHandler(w http.ResponseWriter, r *http.Request) {
	entities, err := h.service.List(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(entities)
}

// CreateHandler handles POST /%s requests.
func (h *%sHandler) CreateHandler(w http.ResponseWriter, r *http.Request) {
	var req Create%sRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	entity, err := h.service.Create(r.Context(), &req)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(entity)
}

// DeleteHandler handles DELETE /%s/{id} requests.
func (h *%sHandler) DeleteHandler(w http.ResponseWriter, r *http.Request) {
	// TODO: Extract ID from URL path
	id := "placeholder-id"

	if err := h.service.Delete(r.Context(), id); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
`, pkgName, base, base, base, name, name, base, name, base, base, baseLower, base, baseLower, baseLower, base, base, base, baseLower, base, base)

	return code, strings.ToLower(base) + "_handler.go"
}

// generateModel generates a data model template.
func (t *CodeGeneratorTool) generateModel(name, pkgName string) (string, string) {
	base := extractBaseName(name)
	baseLower := strings.ToLower(base)
	code := fmt.Sprintf(`// Code generated by picoclaw codegen. DO NOT EDIT.
// Source: pkg/tools/codegen.go

package %s

import "time"

// %s represents a %s entity in the system.
type %s struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time

	// Add fields below
	Name        string
	Description string
	Status      string
}

// TableName returns the database table name for %s.
func (m *%s) TableName() string {
	return "%s"
}

// Validate validates the %s entity.
func (m *%s) Validate() error {
	// TODO: Add validation logic
	return nil
}

// BeforeCreate is called before inserting a new %s.
func (m *%s) BeforeCreate() error {
	now := time.Now()
	m.CreatedAt = now
	m.UpdatedAt = now
	return nil
}

// BeforeUpdate is called before updating an existing %s.
func (m *%s) BeforeUpdate() error {
	m.UpdatedAt = time.Now()
	return nil
}
`, pkgName, base, base, base, base, base, baseLower, base, base, base, base, base, base)

	return code, strings.ToLower(base) + "_model.go"
}

// generateConfig generates a configuration template.
func (t *CodeGeneratorTool) generateConfig(name, pkgName string) (string, string) {
	base := extractBaseName(name)
	envPrefix := strings.ToUpper(strings.ReplaceAll(name, ".", "_"))
	code := fmt.Sprintf(`// Code generated by picoclaw codegen. DO NOT EDIT.
// Source: pkg/tools/codegen.go

package %s

import (
	"encoding/json"
	"os"
)

// %sConfig holds configuration for %s.
type %sConfig struct {
	Enabled     bool
	APIKey      string
	Endpoint    string
	Timeout     int
	MaxRetries  int
}

// Default%sConfig returns default configuration.
func Default%sConfig() *%sConfig {
	return &%sConfig{
		Enabled:    true,
		Timeout:    30,
		MaxRetries: 3,
	}
}

// Load%sConfig loads configuration from file.
func Load%sConfig(path string) (*%sConfig, error) {
	cfg := Default%sConfig()

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return nil, err
	}

	if err := json.Unmarshal(data, cfg); err != nil {
		return nil, err
	}

	return cfg, nil
}

// Validate validates the configuration.
func (c *%sConfig) Validate() error {
	// TODO: Add validation logic
	return nil
}

// Environment variables:
//   - %s_ENABLED
//   - %s_API_KEY
//   - %s_ENDPOINT
//   - %s_TIMEOUT
//   - %s_MAX_RETRIES
`, pkgName, base, base, base, base, base, base, base, base, base, base, base, base, envPrefix, envPrefix, envPrefix, envPrefix, envPrefix)

	return code, strings.ToLower(base) + "_config.go"
}

// extractBaseName extracts the base name from a compound name.
// E.g., "UserService" -> "User", "OrderHandler" -> "Order"
func extractBaseName(name string) string {
	// Find common suffixes
	suffixes := []string{"Service", "Handler", "API", "Config", "Manager", "Controller"}

	for _, suffix := range suffixes {
		if strings.HasSuffix(name, suffix) {
			return strings.TrimSuffix(name, suffix)
		}
	}

	return name
}
